### ISSUE TITLE
update bootstrap to v4

### ISSUE THREAD

**Issue by kenany** [MemeLabs/Rustla2#108]
Changes that are known to affect us:

  - glyphicons are no longer included
  - `.col-xs-*` is now just `.col-*`
  - `.navbar-default` is now `.navbar-light`
  - `.navbar-form` has been removed in favor of `.form-inline`

**Comment by xDashh** [comment]
Does this somehow affect (or simplify) https://github.com/MemeLabs/Rustla2/issues/68 ?
