### ISSUE TITLE
Improve frontpage loading time

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#125]
With the addition of https://github.com/MemeLabs/Rustla2/pull/124 the (perceptible) load time of the frontpage (even for anonymous users) has increased a lot since display of any api data is delayed until the profile data is fetched.

Fetching should be done async(?), and the frontpage displayed immediately (as has been the case before). Once the profile data is loaded, update the frontpage to display whatever changes should be displayed.

Longer-term solution would be to "cache" profile data in local storage, and compare for changes after fetching succeeded.

**Comment by KenanY** [comment]
When I'm not logged in, I don't see any requests made to `/profile`, and from the code it does look like the profile will only be fetched if the user is logged in. So, for anon users, something else must be causing the slowdown.

For logged-in users, yes, the request to `/profile` is indeed blocking the rendering of the streams (~500ms for me on good internet), and this should be fixed.

**Comment by slugalisk** [comment]
We can load the home page without `/profile` can't we? Or at least open the ws connection at the same time so we don't have to wait for both?

There isn't a lot we can do to improve API RTT for US viewers with the server in Europe. Maybe the core UI assets could load from a service worker? That would improve first paint time for responses from cache by around 500ms.

**Comment by KenanY** [comment]
We can definitely load the streams list without the call to `/profile` completing. The `Streams` component should _not_ `renderNothing()` while the profile is fetching; instead, it should just look at the `showHiddenStreams` prop it is given. This is derived from the state which will be updated whenever the request completes.

**Comment by xDashh** [comment]
For me the loading time (from what i remember) is still quite a bit higher than it was before. Is the loading of /ws maybe waiting for some other event? https://i.imgur.com/LwksqNw.png
Or does anyone else think that time has normalized since the last update?

**Comment by JoannesJ** [comment]
Noticed the weird idle time as well.
I'm pretty sure it is this: https://github.com/pladaria/reconnecting-websocket/issues/91

**Comment by JoannesJ** [comment]
This is 150kb compared to the original 400kb, should also help with load times.

![jigglymonkey](https://user-images.githubusercontent.com/13875387/51047156-1fa41400-15c8-11e9-843d-faeb3fa58d1f.png)

**Comment by 11k** [comment]
You're right, it's still a lot slower than before. Even if everything's running on localhost where calls to `/profile` return in less than 50ms. I checked out f1d31e7c98782c202e92c74d3603d55830ed938a (pre-#124) and tried running that--same thing.

**Comment by slugalisk** [comment]
After adding the websocket option from the bug @11k linked it's back to 1-1.5s from us-west. If we want it to be faster https://developers.google.com/web/tools/workbox/ or some other service worker framework would get us to 3-500ms...
