### ISSUE TITLE
allow cross-origin requests to backend API

### ISSUE THREAD

**Issue by KenanY** [MemeLabs/Rustla2#153]
Serving the strims frontend locally, pointing to the production backend API, fails to render stream pages because:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://strims.gg/api/streamer/username_here. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by xDashh** [comment]
Although I'm not sure in which case it would be useful for deving with the production API, this should be resolved by https://github.com/MemeLabs/Rustla2/commit/81c003da7c42bfc8a53e8634ac0d833525ff7f92.

**Comment by KenanY** [comment]
Useful because then I don't need an instance of the backend running locally 😄
