### ISSUE TITLE
Display afk streams

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#197]
Streams with only afk viewers should be shown with "0" instead of being completely removed/hidden, if possible.

**Comment by KenanY** [comment]
Moving to backend as that is where this filtering occurs.

**Comment by xDashh** [comment]
I think the frontend is being told: afk-users: X, non-afk-users: Y, but currently only cares about Y for the decision to display information on the frontpage. So this concerns frontend, if I remember the intend of the issue correctly.

**Comment by KenanY** [comment]
Yup but if Y = 0 (no non-afk viewers) then the stream is filtered out in the backend and not provided to the frontend at all.

**Comment by xDashh** [comment]
Oh really? :thinking: fair enough. Maybe frontend already works then if that was adjusted, not sure.
