### ISSUE TITLE
Registration name check not updated

### ISSUE THREAD

**Issue by Oreganon** [MemeLabs/Rustla2#209]
Somebody was able to name themselves oskrappa breaking emote rendering https://i.imgur.com/fshZEYD.png

Normally names close to emote names are not allowed.

**Comment by KenanY** [comment]
Hmm I wonder if that particular emote (and possibly others) are missing from [the configuration setting](https://github.com/MemeLabs/Rustla2/blob/5ae3004/.env.example#L70-L71)?

**Comment by jbpratt78** [comment]
@KenanY seems like this was the issue. @RightToBearArmsLOL tried to rename me after I updated the production list and restarted the server, it threw an error like expected.
