### ISSUE TITLE
CSS not properly filling window on Safari

### ISSUE THREAD

**Issue by ILiedAboutCake** [MemeLabs/Rustla2#21]
Version 10.0.3 (12602.4.8)
macOS Sierra 10.12.3

Does not fill whole window :(

https://cdn.discordapp.com/attachments/268547141721522178/286338651208548353/Screen_Shot_2017-02-28_at_22.27.04.png

**Comment by xDashh** [comment]
Issue applied to old version. If still happening, let us know.
