### ISSUE TITLE
Fix new chat feature

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#219]
https://github.com/MemeLabs/Rustla2/pull/212

breaks:
 - being able to close the chat
 - the frontpage footer is distorted (single line now. Used to be a block that displayed the lines on the right side entirely)

wanted:
 - ability to re-open the chat on the main page once it has been closed there

**Comment by xDashh** [comment]
Assigning @KenanY since he was involved, actual fix will probably be done by @x-Xymos

**Comment by x-Xymos** [comment]
I'll look into it tomorrow.

> the frontpage footer is distorted (single line now. Used to be a block that displayed the lines on the right side entirely)
This was an intended change by me because the footer was otherwise taking up too much vertical space and now looks a lot cleaner in my opinion

**Comment by x-Xymos** [comment]
Note for tomorrow: reduce the element spacing in the footer and put the discord button somewhere in the header

**Comment by xDashh** [comment]
New footer is also present on the streams ( e.g. `/memestreamer` ) which is unexpected and occupying space.

Being able to close stream and keep it closed is something I'd very much want to allow users to replicated the old behaviour in case they prefer it.

**Comment by KenanY** [comment]
> New footer is also present on the streams ( e.g. `/memestreamer`)

Ah that's the one type of stream I didn't test before merge. In my mind I didn't think they would appear any differently from other streams; maybe just missing a `showFooter(false)` somewhere 🤔

**Comment by x-Xymos** [comment]
The footer is closed when the Stream.jsx component mounts, I'm not sure why it's not working for those type of streams

**Comment by x-Xymos** [comment]
Ahh I know, 
`if (streamer) {
        document.title = `${streamer} - Strims`;
        this.props.setStream(streamer);
        this.props.fetchProfileIfLoggedIn();
        return;
      }`

It's because it returns before the footer is closed

**Comment by x-Xymos** [comment]
Does anyone know why I'm getting this error when trying to log into my s.gg account or view a registered stream page https://i.imgur.com/fy3qKOS.png
I followed the readme and did all the steps like creating the twitch client, adding the jwt token etc.

**Comment by xDashh** [comment]
Not sure about that atm, but you can point your local instance to use the production API in the environment file which should suffice for frontend testing afaik.

**Comment by SmCTwelve** [comment]
Thumbnails are much smaller because of the chat, even moreso if you make the chat wider than the 400px default. I haven't used Bootsrap in years, but it appears the chat embed isn't part of the 12-column layout? So everything on the left inside the stream-embed container being squeezed? 

The thumbnail components are meant to take up 2 columns on large screens (`col-lg-2`) which should equate to 16.6% screen width, but rather the overall container width has been reduced because of the chat so they have even less space. At least on a 1080p screen or below.

**Comment by x-Xymos** [comment]
Ftwpala from chat opened the site on his phone and for some reason his chat and content was flipped, refreshing didn't fix. He uses a huawei p20 https://i.imgur.com/HXFTMqa.jpg 
I tried all different phone dimensions and they were fine.

[Also in mobile view the icon for the navbar collapse menu isn't showing anymore, I swear it was working this morning, it works on my other commit though not sure what's going on.](https://i.imgur.com/fIHZJi5.png)

**Comment by x-Xymos** [comment]
I found the issue, he has left chat on and it flips the layout.
