### ISSUE TITLE
Afreeca streams won't load

### ISSUE THREAD

**Issue by Venats** [MemeLabs/Rustla2#22]
tried viewing Sea's afreeca stream but it wouldn't load

looks like might have something to do with https since for example i can load play.afreecatv.com/yuambo/embed

but 

https://play.afreecatv.com/yuambo/embed
won't load.

**Comment by blushies** [comment]
They won't until Afreeca supports https

**Comment by xDashh** [comment]
More than a year later afreeca still doesn't support https for the stream itself which prevents embedding into a https site. Closing because we can't do anything about it.
