### ISSUE TITLE
login from stream page yields unhandled rejection

### ISSUE THREAD

**Issue by KenanY** [MemeLabs/Rustla2#42]
Steps to reproduce:

  1. Be logged out
  2. Go to any stream (might have to be the only viewer of that stream?)
  3. Click Login button
  4. The following stack trace will appear serverside:

```
Unhandled rejection TypeError: Cannot read property 'service' of null
    at /srv/rustla2/lib/api/websocket.js:72:71
    at Generator.next (<anonymous>)
    at step (/srv/rustla2/lib/api/websocket.js:33:191)
    at /srv/rustla2/lib/api/websocket.js:33:361
    at tryCatcher (/srv/rustla2/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by KenanY** [comment]
This may not be an issue anymore with the C++ backend. Need to check.

**Comment by xDashh** [comment]
Pretty sure this was a js-backend issue. If it pops up again feel free to reopen.
