### ISSUE TITLE
No npm start

### ISSUE THREAD

**Issue by Rantahu** [MemeLabs/Rustla2#55]
Yo peeps, there isn't a npm start script. In the readme should it say `npm run dev-server` for running locally? Also there should be a info on how to run it for production. I can add those to the readme if others agree.

**Comment by KenanY** [comment]
Yeah, those instructions need to be updated. It should be something like:

  1. `npm run build`
  2. run the API server, see `api/README.md` (which also serves the frontend at `localhost:<PORT>`

At the moment, `npm run dev-server` will just serve the frontend, but without a backend not much would work.
