### ISSUE TITLE
chat display is blank if selected chat does not exist

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#70]
If some chat is selected as preference that doesn't exist on some page you visit, the chat is blank (e.g. select twitch chat on some page, then visit an angelthump stream).

Proposed fix: if selected chat does not exist on the current page, default to no/disabled chat (alternative: default to strims chat).

~ As reported and discussed in discord.

**Comment by xDashh** [comment]
Not applicable (anymore?). Front-end only seems to remember whether any chat is opened.

**Comment by slugalisk** [comment]
@xDashh yeah, i fixed this
