### ISSUE TITLE
Advanced m3u8 live detection

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#77]
Once https://github.com/MemeLabs/Rustla2/issues/69 is done, try to detect if a m3u8 stream is live by checking response code (200 vs. other) and possibly changes in the response over time (links to .ts files?). The latter might be too complicated for the benefit.

**Comment by KenanY** [comment]
At least the response code checks will be done in https://github.com/MemeLabs/Rustla2/pull/78.
