### ISSUE TITLE
update services

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#86]
Add support for

~~- [ ] steam.tv~~
- [x] mixer.com

Drop support for

- [x] Afreeca
- [x] Dailymotion
- [x] Chaturbate (unused and bad embed support)

Reminder to add autoplay/chat to the embed, if it isn't by default:
- [x] See/Update https://github.com/MemeLabs/Rustla2/wiki/Updating-Functionality/

**Comment by jbpratt78** [comment]
Notes for later, or someone else.
### Mixer
- ``` https://mixer.com/embed/player/MAGNETRON?disableLowLatency=1 ```
- ``` https://mixer.com/embed/chat/MAGNETRON ```

### Steam.tv
###### will search more later for embed links
-
