### ISSUE TITLE
Reminder Issue for FAQ

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#87]
https://github.com/MemeLabs/Rustla2/wiki/Chat-FAQ

- Eventually move most/all of the content to Discord.
- Actually fix the "known issues" (should create new issues)

**Comment by KenanY** [comment]
Move or copy? I like having the rules here so that one doesn't need a Discord account to read them.

**Comment by xDashh** [comment]
Needs some consideration. At least the list of chat mods seems strange to me to have on a public GitHub. I would like to keep it mostly technical on the GitHub...

**Comment by slugalisk** [comment]
we could make a static page on the site for it

**Comment by xDashh** [comment]
Moving to Discord for now. Selected info can be moved to a static page later.
