### ISSUE TITLE
fix chat embeds

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#90]
- youtube live chat seems to be broken because of (new?) Framing-Policies.
- Some other supported services are lacking chat embeds. (need to investigate which are worth adding)

cf. list on bottom: https://github.com/MemeLabs/Rustla2/wiki/Updating-Functionality/

**Comment by jbpratt78** [comment]
https://support.google.com/youtube/answer/2524549?hl=en

**Comment by xDashh** [comment]
Fixed by https://github.com/MemeLabs/Rustla2/commit/a0062706a5af86e7c414b43551643ecb9f7614ab and (maybe more importantly) relaxing the `Referrer-Policy` of the main site. Youtube expects the domain argument to match it...
